import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ?? AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'ResQ',
      'current_location': 'Current Location',
      'locating': 'Locating...',
      'good_morning': 'Good morning.',
      'good_afternoon': 'Good afternoon.',
      'good_evening': 'Good evening.',
      'greeting_sub': 'Here is the latest status for your area.',
      'flood_risk': 'CURRENT FLOOD RISK',
      'medium_risk': 'MEDIUM',
      'risk_elevated': 'Elevated',
      'risk_desc': 'Stay alert and monitor updates. Water levels in nearby rivers are rising slowly.',
      'view_risk_map': 'View Risk Map',
      'report_incident': 'Report Incident',
      'find_shelter': 'Find Shelter',
      'emergency_contacts': 'Emergency Contacts',
      'latest_alerts': 'Latest Alerts',
      'view_all': 'View All',
      'nearby_shelters': 'Nearby Shelters',
      'road_closure': 'ROAD CLOSURE',
      'alert_desc': 'Main Street bridge is temporarily closed due to rising waters.',
      'emergency_hotlines': 'Emergency Hotlines',
      'disaster_control': 'Disaster Control Room',
      'ambulance_rescue': 'Ambulance & Rescue',
      'fire_force': 'Fire Force',
      'home': 'Home',
      'map': 'Map',
      'shelters': 'Shelters',
      'report': 'Report',
      'profile': 'Profile',
      'dark_mode': 'Dark Mode',
      'language': 'Language / ഭാഷ',
      'select_language': 'Select App Language',
      'location_sharing': 'Location Sharing',
      'active_status': 'Active Status',
      'emergency_safety': 'EMERGENCY & SAFETY',
      'app_offline_access': 'APP & OFFLINE ACCESS',
      'shelter_locator': 'Shelter Locator',
      'map_view': 'Map View',
      'search_shelters': 'Search for shelters by name or location...',
      'nearest': 'Nearest',
      'available': 'Available',
      'medical': 'Medical',
      'pets': 'Pets',
      'first_aid': 'First Aid',
      'water': 'Water',
      'pets_allowed': 'Pets Allowed',
      'capacity': 'Capacity',
      'away': 'away',
      'view_details': 'View Details',
      'directions': 'Directions',
      'shelter_details': 'Shelter Details',
      'get_directions': 'Get Directions',
      'occupancy_status': 'Occupancy\nStatus',
      'filling_fast': 'Filling\nFast',
      'beds': 'beds',
      'available_facilities': 'Available Facilities',
      'food': 'Food',
      'restrooms': 'Restrooms',
      'power': 'Power',
      'wifi': 'Wi-Fi',
      'contact_info': 'Contact Information',
      'critical_alert': 'Critical Alert',
      'navigate_now': 'Navigate Now',
      'standard_layer': 'Standard map layer activated',
      'flood_overlay': 'Flood overlay refreshed',
      'shelters_layer': 'Shelters layer enabled',
      'location_permission_required': 'Location permission required',
      'view_live_map': 'View Live Map',
      'submit_report': 'Submit Report',
      'upload_photo': 'Upload Photo',
      'description': 'Description',
      'password_reset_sent': 'Password reset instructions sent to your email!',
      'send_link': 'Send Link',
      'login': 'Login',
      'signup': 'Sign Up',
      'logout': 'Logout',
      'location_disabled': 'Location services are disabled. Please enable them in your device settings.',
      'location_denied': 'Location permissions are denied. We cannot fetch your current city.',
      'location_permanently_denied': 'Location permissions are permanently denied, we cannot request permissions.',
      'profile_updated': 'Profile updated successfully!',
      'shelter_details_copied': 'Shelter details for ',
      'copied_to_clipboard': ' copied to clipboard!',
      'sample_address': '124 Main Street, Metro City',
      'sample_phone': '1-800-SAFE-911',
      'intake_time': 'Intake: 24/7',
      'door_lock_time': 'Doors lock at 10 PM',
      'shelter_critical_alert': 'Please enter through the North Entrance only. South access is currently blocked due to debris. Have your ID ready for quick processing.',
      'forgot_password': 'Forgot Password?',
      'password_reset_instructions_se': 'Password reset instructions sent to your email!',
      'cancel': 'Cancel',
      'enter_your_registered_email_or': 'Enter your registered email or phone number to receive a recovery link.',
      'reset_password': 'Reset Password',
      'access_your_emergency_response': 'Access your emergency response dashboard.',
      'resq': 'ResQ',
      'empty_string': '•',
      'location_permissions_are_perma': 'Location permissions are permanently denied, we cannot request permissions.',
      'location_permissions_are_denie': 'Location permissions are denied. We cannot fetch your current city.',
      'location_services_are_disabled': 'Location services are disabled. Please enable them in your device settings.',
      '101': '101',
      '108_toll_free': '108 (Toll-Free)',
      '1077_91_474_2794002': '1077 / +91 474 2794002',
      'are_you_sure_you_want_to_log_o': 'Are you sure you want to log out of ResQ?',
      'confirm_logout': 'Confirm Logout',
      'save_changes': 'Save Changes',
      'edit_profile': 'Edit Profile',
      'loading_predictive_models': 'Loading predictive models...',
      'initializing_core_systems': 'INITIALIZING CORE SYSTEMS',
      'predict_respond_recover': 'Predict. Respond. Recover.',
      '1h_ago': '1h ago',
      'capacity_120_400_food_and_medi': 'Capacity: 120/400. Food and medical aid available.',
      'shelter_opened_govt_high_schoo': 'Shelter Opened: Govt High School',
      '10m_ago': '10m ago',
      'water_levels_rising_near_river': 'Water levels rising near river basin. Evacuate to high ground.',
      'flood_warning_kollam_sector_4': 'Flood Warning - Kollam Sector 4',
      'emergency_broadcasts': 'Emergency Broadcasts',
    },
    'ml': {
      'app_title': 'ResQ',
      'current_location': 'നിലവിലെ സ്ഥലം',
      'locating': 'സ്ഥലം കണ്ടെത്തുന്നു...',
      'good_morning': 'സുപ്രഭാതം.',
      'good_afternoon': 'ഉച്ചവന്ദനം.',
      'good_evening': 'സന്ധ്യാവന്ദനം.',
      'greeting_sub': 'നിങ്ങളുടെ പ്രദേശത്തെ ഏറ്റവും പുതിയ വിവരം താഴെ കാണാം.',
      'flood_risk': 'നിലവിലെ വെള്ളപ്പൊക്ക സാധ്യത',
      'medium_risk': 'മിതമായത്',
      'risk_elevated': 'ശ്രദ്ധിക്കുക',
      'risk_desc': 'ജാഗ്രത പാലിക്കുക. സമീപത്തെ പുഴകളിൽ ജലനിരപ്പ് ഉയരുന്നു.',
      'view_risk_map': 'ഭൂപടം കാണുക',
      'report_incident': 'വിവരം അറിയിക്കുക',
      'find_shelter': 'അഭയകേന്ദ്രം തിരയുക',
      'emergency_contacts': 'അടിയന്തര നമ്പറുകൾ',
      'latest_alerts': 'അടിയന്തര മുന്നറിയിപ്പുകൾ',
      'view_all': 'എല്ലാം കാണുക',
      'nearby_shelters': 'അടുത്തുള്ള അഭയകേന്ദ്രങ്ങൾ',
      'road_closure': 'റോഡ് ഗതാഗതം തടസ്സപ്പെട്ടു',
      'alert_desc': 'വെള്ളപ്പൊക്കം കാരണം പ്രധാന പാലം അടച്ചിട്ടിരിക്കുന്നു.',
      'emergency_hotlines': 'അടിയന്തര സഹായ നമ്പറുകൾ',
      'disaster_control': 'ദുരന്തനിവാരണ കൺട്രോൾ റൂം',
      'ambulance_rescue': 'ആംബുലൻസ് & രക്ഷാപ്രവർത്തനം',
      'fire_force': 'ഫയർ ഫോഴ്സ്',
      'home': 'ഹോം',
      'map': 'മാപ്പ്',
      'shelters': 'ഷെൽട്ടറുകൾ',
      'report': 'റിപ്പോർട്ട്',
      'profile': 'പ്രൊഫൈൽ',
      'dark_mode': 'ഡാർക്ക് മോഡ്',
      'language': 'ഭാഷ / Language',
      'select_language': 'ആപ്പ് ഭാഷ തിരഞ്ഞെടുക്കുക',
      'location_sharing': 'ലൊക്കേഷൻ പങ്കിടൽ',
      'active_status': 'സജീവ അവസ്ഥ',
      'emergency_safety': 'അടിയന്തര സുരക്ഷ',
      'app_offline_access': 'ആപ്പ് ക്രമീകരണങ്ങൾ',
      'shelter_locator': 'അഭയകേന്ദ്രം തിരയൽ',
      'map_view': 'മാപ്പ് കാണുക',
      'search_shelters': 'പേരോ സ്ഥലമോ ഉപയോഗിച്ച് അഭയകേന്ദ്രം തിരയുക...',
      'nearest': 'അടുത്തുള്ളത്',
      'available': 'ലഭ്യമായത്',
      'medical': 'മെഡിക്കൽ',
      'pets': 'വളർത്തുമൃഗങ്ങൾ',
      'first_aid': 'പ്രഥമ ശുശ്രൂഷ',
      'water': 'വെള്ളം',
      'pets_allowed': 'വളർത്തുമൃഗങ്ങളെ അനുവദിക്കുന്നു',
      'capacity': 'ശേഷി',
      'away': 'അകലെ',
      'view_details': 'കൂടുതൽ വിവരങ്ങൾ',
      'directions': 'വഴികാട്ടി',
      'shelter_details': 'അഭയകേന്ദ്രത്തിന്റെ വിവരങ്ങൾ',
      'get_directions': 'വഴി അറിയുക',
      'occupancy_status': 'അധിവാസ\nനില',
      'filling_fast': 'വേഗം\nനിറയുന്നു',
      'beds': 'കിടക്കകൾ',
      'available_facilities': 'ലഭ്യമായ സൗകര്യങ്ങൾ',
      'food': 'ഭക്ഷണം',
      'restrooms': 'വിശ്രമമുറികൾ',
      'power': 'വൈദ്യുതി',
      'wifi': 'വൈ-ഫൈ',
      'contact_info': 'ബന്ധപ്പെടാനുള്ള വിവരങ്ങൾ',
      'critical_alert': 'അടിയന്തര മുന്നറിയിപ്പ്',
      'navigate_now': 'ഇപ്പോൾ നാവിഗേറ്റ് ചെയ്യുക',
      'standard_layer': 'സ്റ്റാൻഡേർഡ് മാപ്പ് ലെയർ സജീവമാക്കി',
      'flood_overlay': 'വെള്ളപ്പൊക്ക ഓവർലേ പുതുക്കി',
      'shelters_layer': 'ഷെൽട്ടറുകൾ ലെയർ സജീവമാക്കി',
      'location_permission_required': 'ലൊക്കേഷൻ അനുമതി ആവശ്യമാണ്',
      'view_live_map': 'തത്സമയ മാപ്പ് കാണുക',
      'submit_report': 'റിപ്പോർട്ട് സമർപ്പിക്കുക',
      'upload_photo': 'ഫോട്ടോ അപ്‌ലോഡ് ചെയ്യുക',
      'description': 'വിവരണം',
      'password_reset_sent': 'പാസ്‌വേഡ് പുനഃസജ്ജമാക്കാനുള്ള നിർദ്ദേശങ്ങൾ നിങ്ങളുടെ ഇമെയിലിലേക്ക് അയച്ചു!',
      'send_link': 'ലിങ്ക് അയയ്ക്കുക',
      'login': 'ലോഗിൻ',
      'signup': 'സൈൻ അപ്പ്',
      'logout': 'ലോഗൗട്ട്',
      'location_disabled': 'ലൊക്കേഷൻ സേവനങ്ങൾ പ്രവർത്തനരഹിതമാണ്. നിങ്ങളുടെ ഉപകരണ ക്രമീകരണങ്ങളിൽ അവ പ്രവർത്തനക്ഷമമാക്കുക.',
      'location_denied': 'ലൊക്കേഷൻ അനുമതികൾ നിഷേധിച്ചു. നിങ്ങളുടെ നിലവിലെ നഗരം വീണ്ടെടുക്കാൻ കഴിയില്ല.',
      'location_permanently_denied': 'ലൊക്കേഷൻ അനുമതികൾ ശാശ്വതമായി നിഷേധിച്ചു, ഞങ്ങൾക്ക് അനുമതികൾ അഭ്യർത്ഥിക്കാൻ കഴിയില്ല.',
      'profile_updated': 'പ്രൊഫൈൽ വിജയകരമായി അപ്‌ഡേറ്റ് ചെയ്‌തു!',
    },
    'hi': {
      'app_title': 'ResQ',
      'current_location': 'वर्तमान स्थान',
      'locating': 'स्थान खोजा जा रहा है...',
      'good_morning': 'शुभ प्रभात।',
      'good_afternoon': 'शुभ दोपहर।',
      'good_evening': 'शुभ संध्या।',
      'greeting_sub': 'आपके क्षेत्र की नवीनतम स्थिति यहाँ है।',
      'flood_risk': 'वर्तमान बाढ़ का जोखिम',
      'medium_risk': 'मध्यम',
      'risk_elevated': 'सावधान',
      'risk_desc': 'सतर्क रहें। नजदीकी नदियों में जलस्तर धीरे-धीरे बढ़ रहा है।',
      'view_risk_map': 'जोखिम मानचित्र देखें',
      'report_incident': 'घटना की रिपोर्ट करें',
      'find_shelter': 'आश्रय स्थल खोजें',
      'emergency_contacts': 'आपतकालीन संपर्क',
      'latest_alerts': 'नवीनतम अलर्ट',
      'view_all': 'सभी देखें',
      'nearby_shelters': 'निकटतम आश्रय स्थल',
      'road_closure': 'सड़क बंद',
      'alert_desc': 'बढ़ते जलस्तर के कारण मुख्य पुल अस्थायी रूप से बंद है।',
      'emergency_hotlines': 'आपतकालीन हेल्पलाइन',
      'disaster_control': 'आपदा नियंत्रण कक्ष',
      'ambulance_rescue': 'एंबुलेंस और बचाव',
      'fire_force': 'दमकल सेवा',
      'home': 'होम',
      'map': 'मानचित्र',
      'shelters': 'आश्रय',
      'report': 'रिपोर्ट',
      'profile': 'प्रोफ़ाइल',
      'dark_mode': 'डार्क मोड',
      'language': 'भाषा / Language',
      'select_language': 'ऐप की भाषा चुनें',
      'location_sharing': 'लोकेशन शेयरिंग',
      'active_status': 'सक्रिय स्थिति',
      'emergency_safety': 'आपातकाल और सुरक्षा',
      'app_offline_access': 'ऐप और ऑफ़लाइन एक्सेस',
      'shelter_locator': 'आश्रय खोजक',
      'map_view': 'मानचित्र दृश्य',
      'search_shelters': 'नाम या स्थान से आश्रय खोजें...',
      'nearest': 'निकटतम',
      'available': 'उपलब्ध',
      'medical': 'चिकित्सा',
      'pets': 'पालतू जानवर',
      'first_aid': 'प्राथमिक चिकित्सा',
      'water': 'पानी',
      'pets_allowed': 'पालतू जानवरों की अनुमति है',
      'capacity': 'क्षमता',
      'away': 'दूर',
      'view_details': 'विवरण देखें',
      'directions': 'दिशा-निर्देश',
      'shelter_details': 'आश्रय विवरण',
      'get_directions': 'दिशा-निर्देश प्राप्त करें',
      'occupancy_status': 'अधिभोग\nस्थिति',
      'filling_fast': 'तेजी से\nभर रहा है',
      'beds': 'बिस्तर',
      'available_facilities': 'उपलब्ध सुविधाएं',
      'food': 'भोजन',
      'restrooms': 'शौचालय',
      'power': 'बिजली',
      'wifi': 'वाई-फाई',
      'contact_info': 'संपर्क जानकारी',
      'critical_alert': 'गंभीर चेतावनी',
      'navigate_now': 'अभी नेविगेट करें',
      'standard_layer': 'मानक मानचित्र परत सक्रिय',
      'flood_overlay': 'बाढ़ ओवरले ताज़ा किया गया',
      'shelters_layer': 'आश्रय परत सक्षम',
      'location_permission_required': 'स्थान अनुमति आवश्यक है',
      'view_live_map': 'लाइव मानचित्र देखें',
      'submit_report': 'रिपोर्ट सबमिट करें',
      'upload_photo': 'फोटो अपलोड करें',
      'description': 'विवरण',
      'password_reset_sent': 'पासवर्ड रीसेट निर्देश आपके ईमेल पर भेजे गए हैं!',
      'send_link': 'लिंक भेजें',
      'login': 'लॉगिन',
      'signup': 'साइन अप',
      'logout': 'लॉग आउट',
      'location_disabled': 'स्थान सेवाएं अक्षम हैं। कृपया उन्हें अपनी डिवाइस सेटिंग में सक्षम करें।',
      'location_denied': 'स्थान अनुमतियाँ अस्वीकार कर दी गई हैं। हम आपका वर्तमान शहर प्राप्त नहीं कर सकते।',
      'location_permanently_denied': 'स्थान अनुमतियाँ स्थायी रूप से अस्वीकार कर दी गई हैं, हम अनुमतियों का अनुरोध नहीं कर सकते।',
      'profile_updated': 'प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!',
    },
    'ta': {
      'app_title': 'ResQ',
      'current_location': 'தற்போதைய இடம்',
      'locating': 'இடம் கண்டறியப்படுகிறது...',
      'good_morning': 'காலை வணக்கம்.',
      'good_afternoon': 'மதிய வணக்கம்.',
      'good_evening': 'மாலை வணக்கம்.',
      'greeting_sub': 'உங்கள் பகுதிக்கான சமீபத்திய நிலைமை இதோ.',
      'flood_risk': 'தற்போதைய வெள்ள ஆபத்து',
      'medium_risk': 'நடுத்தரம்',
      'risk_elevated': 'எச்சரிக்கை',
      'risk_desc': 'விழிப்புடன் இருங்கள். அருகிலுள்ள ஆறுகளில் நீர்மட்டம் உயர்கிறது.',
      'view_risk_map': 'வரைபடம் பார்க்க',
      'report_incident': 'தகவல் அளிக்கவும்',
      'find_shelter': 'முகாம் கண்டறிக',
      'emergency_contacts': 'அவசர தொடர்புகள்',
      'latest_alerts': 'சமீபத்திய எச்சரிக்கைகள்',
      'view_all': 'அனைத்தும் பார்க்க',
      'nearby_shelters': 'அருகிலுள்ள நிவாரண முகாம்கள்',
      'road_closure': 'பாதை அடைப்பு',
      'alert_desc': 'வெள்ளப்பெருக்கு காரணமாக பிரதான பாலம் மூடப்பட்டுள்ளது.',
      'emergency_hotlines': 'அவசர உதவி எண்கள்',
      'disaster_control': 'பேரிடர் கட்டுப்பாட்டு அறை',
      'ambulance_rescue': 'ஆம்புலன்ஸ் & மீட்பு படை',
      'fire_force': 'தீயணைப்பு படை',
      'home': 'முகப்பு',
      'map': 'வரைபடம்',
      'shelters': 'முகாம்கள்',
      'report': 'அறிக்கை',
      'profile': 'சுயவிவரம்',
      'dark_mode': 'டார்க் மோட்',
      'language': 'மொழி / Language',
      'select_language': 'பயன்பாட்டு மொழியைத் தேர்ந்தெடுக்கவும்',
      'location_sharing': 'இடப் பகிர்வு',
      'active_status': 'செயலில் உள்ள நிலை',
      'emergency_safety': 'அவசரம் மற்றும் பாதுகாப்பு',
      'app_offline_access': 'செயலி அமைப்புகள்',
      'shelter_locator': 'முகாம் கண்டறிவான்',
      'map_view': 'வரைபடப் பார்வை',
      'search_shelters': 'பெயர் அல்லது இடம் மூலம் முகாம்களைத் தேடுக...',
      'nearest': 'அருகிலுள்ள',
      'available': 'கிடைக்கிறது',
      'medical': 'மருத்துவம்',
      'pets': 'செல்லப்பிராணிகள்',
      'first_aid': 'முதலுதவி',
      'water': 'தண்ணீர்',
      'pets_allowed': 'செல்லப்பிராணிகளுக்கு அனுமதி உண்டு',
      'capacity': 'திறன்',
      'away': 'தொலைவில்',
      'view_details': 'விவரங்களைப் பார்க்க',
      'directions': 'வழிகாட்டல்',
      'shelter_details': 'முகாம் விவரங்கள்',
      'get_directions': 'வழிமுறைகளைப் பெறுக',
      'occupancy_status': 'குடியிருப்பு\nநிலை',
      'filling_fast': 'விரைவாக\nநிரம்புகிறது',
      'beds': 'படுக்கைகள்',
      'available_facilities': 'கிடைக்கக்கூடிய வசதிகள்',
      'food': 'உணவு',
      'restrooms': 'ஓய்வறைகள்',
      'power': 'மின்சாரம்',
      'wifi': 'வைஃபை',
      'contact_info': 'தொடர்பு தகவல்',
      'critical_alert': 'முக்கிய எச்சரிக்கை',
      'navigate_now': 'இப்போது வழிசெலுத்துக',
      'standard_layer': 'நிலையான வரைபட அடுக்கு செயல்படுத்தப்பட்டது',
      'flood_overlay': 'வெள்ள மேலடுக்கு புதுப்பிக்கப்பட்டது',
      'shelters_layer': 'முகாம்கள் அடுக்கு இயக்கப்பட்டது',
      'location_permission_required': 'இட அனுமதி தேவை',
      'view_live_map': 'நேரடி வரைபடத்தைக் காண்க',
      'submit_report': 'அறிக்கையைச் சமர்ப்பிக்கவும்',
      'upload_photo': 'புகைப்படத்தை பதிவேற்றவும்',
      'description': 'விளக்கம்',
      'password_reset_sent': 'கடவுச்சொல் மீட்டமைப்பு வழிமுறைகள் உங்கள் மின்னஞ்சலுக்கு அனுப்பப்பட்டுள்ளன!',
      'send_link': 'இணைப்பை அனுப்புக',
      'login': 'உள்நுழைக',
      'signup': 'பதிவு செய்க',
      'logout': 'வெளியேறு',
      'location_disabled': 'இருப்பிடச் சேவைகள் முடக்கப்பட்டுள்ளன. உங்கள் சாதன அமைப்புகளில் அவற்றை இயக்கவும்.',
      'location_denied': 'இட அனுமதிகள் மறுக்கப்பட்டுள்ளன. உங்கள் தற்போதைய நகரத்தை எங்களால் பெற முடியாது.',
      'location_permanently_denied': 'இட அனுமதிகள் நிரந்தரமாக மறுக்கப்பட்டுள்ளன, எங்களால் அனுமதிகளைக் கோர முடியாது.',
      'profile_updated': 'சுயவிவரம் வெற்றிகரமாக புதுப்பிக்கப்பட்டது!',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ml', 'hi', 'ta'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
